### ISSUE TITLE
Batch forward

### ISSUE THREAD

**Issue by xyzhang626** [staghado/vit.cpp#5]
Hey @staghado thanks for the great work!

I'm wondering whether you have any idea about implementing the batched images forward given batch size > 1. 

I notice the batch processing in llama.cpp seems pretty different. No batch dim is involved in the forward pass. I also propose a [discussion] 
 (https://github.com/ggerganov/llama.cpp/discussions/4371) there. Do you have any idea about this? Thanks in advance!

**Comment by staghado** [comment]
Hey @xyzhang626,

I think for edge inference, the case that we want to optimize is the case of `batch_size = 1`. Like when a user is interacting with llama.cpp, the user sends only one prompt at a time.

A batched version can be implemented but will require some modification to the graph. The tensors in GGML are up to 4 dimensions so it can be done.
See [clip.cpp](https://github.com/monatis/clip.cpp/blob/8f348725271db67517de871dea4a4e8a159e664f/clip.cpp#L1075) for an example of a batched forward pass.

**Comment by xyzhang626** [comment]
Thanks point me to the helpful repo! It's a bit tricky to learn to write a ggml model inference since there is no doc. Have to learn from the examples, appreciate your help!
