### ISSUE TITLE
/home/shared/vit.cpp/tests/benchmark.cpp:4:10: fatal error: nlohmann/json.hpp: No such file or directory 

### ISSUE THREAD

**Issue by twmht** [staghado/vit.cpp#8]
did you miss the dependency nlohmann/json.hpp?

**Comment by staghado** [comment]
That is correct! I will add it

**Comment by staghado** [comment]
I have added the JSON package in the CMakeLists.txt and made it optional. If you want to build the benchmark executable add `cmake -BUILD_BENCHMARK=ON ..;`

**Comment by twmht** [comment]
@staghado 

thank you

**Comment by twmht** [comment]
@staghado 

how did you install json by making this line([nlohmann_json ](https://github.com/staghado/vit.cpp/blob/main/CMakeLists.txt#L46)) works?

**Comment by staghado** [comment]
Check the official documentation of that specific library on how to install on your specific platform.
